# Conclusions {#conclusions}


Ethiopia's growing regions span an unusually broad set of climatic spaces, spanning a variety of zones from rain-forests, Mediterranean ecosystems, to semi-arid deserts. Given the well documented sensitivity to changes due to climate change, Ethiopia must look for ways to enhance the productivity of all its lands, especially those now considered marginal. This broadening of the climatic space that is productively used for agriculture will enhance household and national resiliency. 

Although not well understood until recently, Ethiopia has a significant problem with acidic soils. Soils with low pH can significantly suppress agricultural yields and may prompt the abandonment of otherwise productive lands. Ethiopia's soils likely became acidic due to long periods of weathering, erosion, intensive use, as well as the additional acidity induced by the application of fertilizers. Additionally, some areas also have significant problems with alkaline soils, which undermine plant productivity in ways very similar to acidity. 

In this study we approach estimating the economic and agricultural viability of soil remediation, through the application of lime, through data-driven methods. We utilize observations of agricultural yields for wheat and barley from the AgSS survey for the 2010-2016 growing seasons. We control for a variety of confounding effects such as weather, other soil properties, management practices, and government interventions. We find that moderately and highly acidic soils significantly undermine yields for both wheat and barley. Moreover, we find evidence on a region by region basis for the economic viability of soil remediation through the application of lime, especially in highly acidic areas. Taken as a whole we find substantial real-world evidence that soil remediation can increase yields and economic outcomes for farmers across its acidic regions. 
